use_frameworks!

target 'DigitalSignVios_Example' do
  pod 'DigitalSignVios', :path => '../'

  target 'DigitalSignVios_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
